server:
  port: 8081
spring:
  datasource:
    username: root
#    password: guoshengkai373
#    password: nhii@lcg_mysql@123
    url: jdbc:mysql://mysql.ngrok.conf.pub:13306/bbs?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
  freemarker:
    cache: false
    charset: utf-8
    suffix: .ftl
mybatis:
  mapper-locations: classpath:/mappers/*.xml
logging:
  level:
    com.aiyi.blog: DEBUG
  file:
    name: logs/bbs.log

aliyun:
  access-key-id: ${alikey}
  access-secret: ${alisec}
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: bbs-app-gsk