server:
  port: 8081
spring:
  datasource:
    username: root
    url: jdbc:mysql://ngrok.conf.pub:4002/bbs?serverTimezone=UTC
    password: root
#    url: jdbc:mysql://172.18.0.2:3306/bbs?serverTimezone=UTC
#    password: guoshengkai373
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    cache: false
    charset: utf-8
    suffix: .ftl
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:/mappers/*.xml
logging:
  level:
    com.aiyi.blog: DEBUG
  file:
    name: logs/bbs.log

aliyun:
  access-key-id: ${alikey}
  access-secret: ${alisec}
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: bbs-app-gsk

alikey: 123
alisec: 123